joint_trajectory_controller:
  ros__parameters:
    joints:
      - jRightElbow_rotx

    interface_name: position
    command_interfaces:
      - position

    state_interfaces:
      - position
      - velocity

human:
  controller_manager:
    ros__parameters:
      update_rate: 1000 # Hz
      use_sim_time: true
  
      joint_trajectory_controller:
        type: joint_trajectory_controller/JointTrajectoryController
  
      joint_state_controller:
        type: joint_state_controller/JointStateController
  
      joint_state_broadcaster:
        type: joint_state_broadcaster/JointStateBroadcaster
