joint_trajectory_controller:
  ros__parameters:
    joints:
      - jRightElbow_rotx

    interface_name: position
    command_interfaces:
      - position

    state_interfaces:
      - position
      - velocity

# http://www.ece.ufrgs.br/~fetter/eng10051/q2d_ros2_control.pdf for effort controller usage
effort_controller:
  ros__parameters:
    joints:
      - jRightElbow_rotx
    #
    # interface_name: effort
    # command_interfaces:
    #   - effort
    #
    # state_interfaces:
    #   - position
    #   - velocity
    #   - effort

human:
  controller_manager:
    ros__parameters:
      update_rate: 1000 # Hz
      use_sim_time: true
  
      effort_controller:
        type: effort_controllers/JointGroupEffortController

      joint_trajectory_controller:
        type: joint_trajectory_controller/JointTrajectoryController
  
      joint_state_controller:
        type: joint_state_controller/JointStateController
  
      joint_state_broadcaster:
        type: joint_state_broadcaster/JointStateBroadcaster
